### ISSUE TITLE
Java backend emits instance call for cross-module extension function

### ISSUE THREAD

**Issue by magx2** [magx2/Capybara#556]
## Summary

The Java backend emits an instance-method call for a Capybara extension function defined in another module. The extension is generated as a static Java method, so the generated caller does not compile.

Observed with Capybara `0.14.0-SNAPSHOT` at commit `cd2dbcc5`.

## Reproduction

Define an extension function in one module:

```cfun
data Position {
    can_move: bool,
}

fun Position.available_moves(): List[int] =
    if this.can_move then [1] else []
```

Import the types/function through that module and use normal extension-call syntax from another module:

```cfun
from /example/Games import { Position }

fun choose(position: Position): List[int] =
    position.available_moves()
```

The concrete Paper Soccer source is:

```cfun
let position = game.positions[ball.to_string()].or_else(free_all_position())
let available_move_directions: List[MoveDirection] =
    position.available_move_directions()
```

`compileCapybara` succeeds.

## Generated declaration

The extension function is correctly emitted in `Games.java` as a static method:

```java
public static List<Games.MoveDirection>
Position_available_move_directions__145_0(Games.Position _this) {
    // ...
}
```

## Actual generated call

The consuming module generates:

```java
List<Games.MoveDirection> available_move_directions =
    position.available_move_directions();
```

This fails in `javac`:

```text
error: cannot find symbol
    position.available_move_directions();
            ^
  symbol:   method available_move_directions()
  location: variable position of type Position
```

## Expected generated call

The backend should lower the extension call to its generated static function:

```java
List<Games.MoveDirection> available_move_directions =
    Games.Position_available_move_directions__145_0(position);
```

An equivalent valid static import and call would also be acceptable.

## Impact

Valid cross-module extension calls pass Capybara compilation but produce uncompilable Java. This worked in an earlier `0.14.0-SNAPSHOT` and appears to be a regression in the current snapshot.
